Disable dpdk when building libpcap
There are incompatible API changes in DPDK that causes build errors. As we are not using dpdk, explicitly disable it.

 gcc -fvisibility=hidden  -fpic -I.  -include rte_config.h -march=corei7 -mrtm -I/usr/include/libnl3 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -DBUILDING_PCAP -Dpcap_EXPORTS -DHAVE_CONFIG_H  -g -O2    -c ./pcap-dpdk.c
      ./pcap-dpdk.c:202:18: error: ‘struct rte_eth_rxmode’ has no member named ‘split_hdr_size’
        202 |                 .split_hdr_size = 0,
            |                  ^~~~~~~~~~~~~~
      ./pcap-dpdk.c:205:28: error: ‘ETH_MQ_TX_NONE’ undeclared here (not in a function); did you mean ‘RTE_ETH_MQ_TX_NONE’?
        205 |                 .mq_mode = ETH_MQ_TX_NONE,
            |                            ^~~~~~~~~~~~~~
            |                            RTE_ETH_MQ_TX_NONE